import './js/yearList';
import './sass/main.scss';
import './js/popular.js';
import './js/filter.js';
import './js/pagination.js';
import './js/search.js';
import './js/search-prediction.js';
import './js/myLibrary.js';
import './js/modal.js';
import "./js/theme-tumbler.js"
import './js/listenerForModal.js'
import './js/languages.js'